### PR TITLE
Add formatting with prettier

### PR DESCRIPTION
**Pull request by yongrenjie**
The first commit adds `prettier` into the repo so that anyone can use it, the second enforces it. Depending on how opinionated we'd like to be we can merge 0, 1, or both of the commits in 🙂

### CODE REVIEW

**Comment by stuartlynn** [comment]
Amazing! I was meaning to do this :-) Just a couple of quick things 

1. It seems to be running on everything including the already minified vendor code. We probably want to have an exclude option for anything in public so that doesn't happen 
2. I think that the guide lines for astro are to use prettier-plugin-astro with prettier (https://docs.astro.build/en/editor-setup/#prettier). It might be worth adding both this and prettier to dev dependencies and running then using npm rather than npx

**Comment by yongrenjie** [comment]
@stuartlynn Got it! - do you want to keep the precommit hook? :)

**Comment by stuartlynn** [comment]
For sure! We just will want to use it to run the dev dependency versions
rather than through npx

**Review by stuartlynn — APPROVED** [review]
Looks good to me. Will merge in

**Pull request merged**
